
export interface WorkflowStep {
  order: number;
  stepName: string;
  defaultDuration?: number;
}

export type Workflow = WorkflowStep[];

export const WORKFLOW_TEMPLATES: Record<string, Workflow> = {
  'Matrimonial Property Suits': [
    { order: 1, stepName: 'Paid consultation + strategy meeting' },
    { order: 2, stepName: 'Quote & instructions & request for documents', defaultDuration: 2 },
    { order: 3, stepName: 'Drafting [interim and/or main suit]', defaultDuration: 7 },
    { order: 4, stepName: 'Approval & signing' },
    { order: 5, stepName: 'Compilation', defaultDuration: 3 },
    { order: 6, stepName: 'Filing', defaultDuration: 1 },
    { order: 7, stepName: 'Draft letter, extract orders, if any', defaultDuration: 1 },
    { order: 8, stepName: 'Apply for date' },
    { order: 9, stepName: 'Serve pleadings, mention/hearing notices and/or orders' },
    { order: 10, stepName: 'File affidavit of service' },
    { order: 11, stepName: 'Share response with client & ask for client’s reply', defaultDuration: 1 },
    { order: 12, stepName: 'Draft response', defaultDuration: 7 },
    { order: 13, stepName: 'Approval & signing' },
    { order: 14, stepName: 'Compile replies', defaultDuration: 2 },
    { order: 15, stepName: 'File', defaultDuration: 1 },
    { order: 16, stepName: 'Serve opposing party' },
    { order: 17, stepName: 'File affidavit of service' },
    { order: 18, stepName: 'Attend Court for Hearing of Application & update client' },
    { order: 19, stepName: 'Prepare Submissions & List of Authorities', defaultDuration: 7 },
    { order: 20, stepName: 'File & serve submissions' },
    { order: 21, stepName: 'Attend Ruling & update client' },
    { order: 22, stepName: 'Extract Order' },
    { order: 23, stepName: 'Share with client and/or serve' },
    { order: 24, stepName: 'Fix a mid-trial strategy meeting' },
    { order: 25, stepName: 'File additional affidavits & documents' },
    { order: 26, stepName: 'Pre-trial prep with client' },
    { order: 27, stepName: 'Trial' },
    { order: 28, stepName: 'Draft submissions', defaultDuration: 7 },
    { order: 29, stepName: 'Attend Judgment/Ruling' },
    { order: 30, stepName: 'Extract Decree & copy of Judgment' },
    { order: 31, stepName: 'Share with client' },
    { order: 32, stepName: 'Upsell/Downsell Post-judgment execution' }
  ],
  'General Dispute Resolution': [
    { order: 1, stepName: 'Paid consultation + strategy meeting' },
    { order: 2, stepName: 'Quote & instructions & request for documents', defaultDuration: 2 },
    { order: 3, stepName: 'Drafting', defaultDuration: 7 },
    { order: 4, stepName: 'Approval & signing' },
    { order: 5, stepName: 'Compiling', defaultDuration: 3 },
    { order: 6, stepName: 'Filing', defaultDuration: 1 },
    { order: 7, stepName: 'Follow up on summons' },
    { order: 8, stepName: 'Serve pleadings & summons' },
    { order: 9, stepName: 'File affidavit of service' },
    { order: 10, stepName: 'Share response with client & ask for client’s reply' },
    { order: 11, stepName: 'Draft response', defaultDuration: 7 },
    { order: 12, stepName: 'Approval & signing' },
    { order: 13, stepName: 'Compile', defaultDuration: 3 },
    { order: 14, stepName: 'File', defaultDuration: 1 },
    { order: 15, stepName: 'Serve opposing party' },
    { order: 16, stepName: 'File affidavit of service' },
    { order: 17, stepName: 'Apply for date for pre-trial (invite or serve afterwards)' },
    { order: 18, stepName: 'Pre-trial prep with client' },
    { order: 19, stepName: 'Trial' },
    { order: 20, stepName: 'Prepare Submissions & List of Authorities', defaultDuration: 7 },
    { order: 21, stepName: 'File & serve submissions' },
    { order: 22, stepName: 'Attend Judgment/Ruling & Update client' },
    { order: 23, stepName: 'Extract Decree & copy of Judgment' },
    { order: 24, stepName: 'Share with client' },
    { order: 25, stepName: 'Extract certified copy of Decree' },
    { order: 26, stepName: 'Upsell/Downsell Post-judgment execution if necessary' }
  ],
  'Estate Planning': [ // Mapped from "Succession Planning"
    { order: 1, stepName: 'Paid consultation' },
    { order: 2, stepName: 'Quote & receive instructions' },
    { order: 3, stepName: 'Drafting', defaultDuration: 7 },
    { order: 4, stepName: 'Approval' },
    { order: 5, stepName: 'Signatures by client and witnesses' },
    { order: 6, stepName: 'Write to executors' },
    { order: 7, stepName: 'Seal and store' }
  ],
  'Parental Responsibility Settlement Agreement': [ // Mapped from "Parental Responsibility Agreement"
    { order: 1, stepName: 'Paid consultation + Strategy meeting' },
    { order: 2, stepName: 'Quote & instructions', defaultDuration: 2 },
    { order: 3, stepName: 'Drafting initial letter &/or proposed PRA', defaultDuration: 4 },
    { order: 4, stepName: 'Approval' },
    { order: 5, stepName: 'Send correspondence to opposing party' },
    { order: 6, stepName: 'Share response' },
    { order: 7, stepName: 'Negotiation session(s) and/or amendment(s)' },
    { order: 8, stepName: 'Parties sign' },
    { order: 9, stepName: 'File Misc. Application to Court', defaultDuration: 3 },
    { order: 10, stepName: 'Serve pleadings' },
    { order: 11, stepName: 'Take date & serve' },
    { order: 12, stepName: 'File Affidavit of service' },
    { order: 13, stepName: 'Attend Court for Hearing' },
    { order: 14, stepName: 'Ruling' },
    { order: 15, stepName: 'Extract orders' },
    { order: 16, stepName: 'Upsell/Downsell succession planning' }
  ],
  'Adoption': [
    { order: 1, stepName: 'Free Consultation+ Instructions + quote' },
    { order: 2, stepName: 'Documents requested', defaultDuration: 1 },
    { order: 3, stepName: 'Drafting done after receiving documents & payment', defaultDuration: 3 },
    { order: 4, stepName: 'Approved and signed', defaultDuration: 1 },
    { order: 5, stepName: 'Compiled and Filed', defaultDuration: 3 },
    { order: 6, stepName: 'Date Applied For (Immediately after filing)' },
    { order: 7, stepName: 'Date Taken & Client informed of date' },
    { order: 8, stepName: 'Serve Adoption Society first hearing', defaultDuration: 2 },
    { order: 9, stepName: 'File Affidavit of Service', defaultDuration: 1 },
    { order: 10, stepName: 'Prep GAL on hearing', defaultDuration: 1 },
    { order: 11, stepName: 'Provide hard copies to court (day before the hearing)' },
    { order: 12, stepName: 'Court Attendance & Update client' },
    { order: 13, stepName: 'Extract Order & share GAL report template with GAL' },
    { order: 14, stepName: 'Serve DCS and inform client', defaultDuration: 1 },
    { order: 15, stepName: 'Follow up client on DCS process' },
    { order: 16, stepName: 'Apply for hearing date' },
    { order: 17, stepName: 'Follow up/secure date' },
    { order: 18, stepName: 'Inform client and GAL ON DATE' },
    { order: 19, stepName: 'File GAL Report' },
    { order: 20, stepName: 'Serve DCS & SOCIETY with hearing notices' },
    { order: 21, stepName: 'Trial prep – inhouse – to confirm everything is in place', defaultDuration: 14 },
    { order: 22, stepName: 'Provide court hard copies of reports & extra documents' },
    { order: 23, stepName: 'Send all parties link' },
    { order: 24, stepName: 'Attend hearing & Update client' },
    { order: 25, stepName: 'Prep adoption order' },
    { order: 26, stepName: 'Attend JUDGEMENT & update client' },
    { order: 27, stepName: 'Apply for Adoption Order & Certified copies' },
    { order: 28, stepName: 'Apply for Adoption Certificate' },
    { order: 29, stepName: 'Apply for Birth Certificate + Verification letter' },
    { order: 30, stepName: 'Apply for Judgement' },
    { order: 31, stepName: 'Release documents' },
    { order: 32, stepName: 'Letter to Adoption Society & DCS' }
  ],
  'Guardianship': [
    { order: 1, stepName: 'Consultation + Instructions + Quote + Request for documents', defaultDuration: 2 },
    { order: 2, stepName: 'Documents received' },
    { order: 3, stepName: 'Drafting', defaultDuration: 3 },
    { order: 4, stepName: 'Approved and signed' },
    { order: 5, stepName: 'Compiling and filing', defaultDuration: 3 },
    { order: 6, stepName: 'Apply for mention date', defaultDuration: 1 },
    { order: 7, stepName: 'Attend mention for directions & Inform clients' },
    { order: 8, stepName: 'Extract Order' },
    { order: 9, stepName: 'Serve Children’s Department & Interested parties' },
    { order: 10, stepName: 'Follow up on report' },
    { order: 11, stepName: 'Apply for & Take hearing date (if court did not issue)' },
    { order: 12, stepName: 'Attend court & Inform client' },
    { order: 13, stepName: 'Extract Orders' },
    { order: 14, stepName: 'Share orders with client' },
    { order: 15, stepName: 'Upsell/Downsell Adoption and/or Estate planning' }
  ],
  'Child Custody and Maintenance': [ // Mapped from "Custody & Maintenance"
    { order: 1, stepName: 'Paid Consultation + Strategy Meeting' },
    { order: 2, stepName: 'Quote & Instructions', defaultDuration: 2 },
    { order: 3, stepName: 'Document collection' },
    { order: 4, stepName: 'Drafting', defaultDuration: 7 },
    { order: 5, stepName: 'Approval and signing' },
    { order: 6, stepName: 'Filing' },
    { order: 7, stepName: 'Follow up on summons' },
    { order: 8, stepName: 'Take a Date (If not given by court)' },
    { order: 9, stepName: 'Serve Opposing party' },
    { order: 10, stepName: 'File Affidavit of Service' },
    { order: 11, stepName: 'Drafting reply', defaultDuration: 7 },
    { order: 12, stepName: 'Approval and signing of replies' },
    { order: 13, stepName: 'File & Serve replies' },
    { order: 14, stepName: 'Court Attendance & Update Client' },
    { order: 15, stepName: 'Draft Submissions', defaultDuration: 7 },
    { order: 16, stepName: 'Court Attendance – Ruling & Update client' },
    { order: 17, stepName: 'Extract Order' },
    { order: 18, stepName: 'Serve Order' },
    { order: 19, stepName: 'Mid-case strategy meeting with client' },
    { order: 20, stepName: 'Comply with Order 11' },
    { order: 21, stepName: 'Trial Preparation' },
    { order: 22, stepName: 'Attend trial and Update client' },
    { order: 23, stepName: 'Draft Submissions', defaultDuration: 14 },
    { order: 24, stepName: 'Attend mention & Update client' },
    { order: 25, stepName: 'Attend Judgment & Update client' },
    { order: 26, stepName: 'Extract Decree' },
    { order: 27, stepName: 'Upsell/Downsell Post Judgment Execution, Other firm services' }
  ],
  'Divorce': [
    { order: 1, stepName: 'Paid Consultation + Strategy Meeting' },
    { order: 2, stepName: 'Quote & Instructions+ Request for documents', defaultDuration: 2 },
    { order: 3, stepName: 'Document collection' },
    { order: 4, stepName: 'Drafting', defaultDuration: 7 },
    { order: 5, stepName: 'Approval and signing' },
    { order: 6, stepName: 'Filing' },
    { order: 7, stepName: 'Pursue Notice to Appear' },
    { order: 8, stepName: 'Serve Opposing Party' },
    { order: 9, stepName: 'File Affidavit of Service' },
    { order: 10, stepName: 'Share reply with client & call for response', defaultDuration: 1 },
    { order: 11, stepName: 'Drafting Replies', defaultDuration: 7 },
    { order: 12, stepName: 'Approval and signing of replies' },
    { order: 13, stepName: 'File response' },
    { order: 14, stepName: 'File application for certificate of compliance & Take a date' },
    { order: 15, stepName: 'Take a date for certificate of compliance' },
    { order: 16, stepName: 'Serve opposing party with certificate of compliance' },
    { order: 17, stepName: 'Court Attendance – certificate of compliance & Update client' },
    { order: 18, stepName: 'Take a date (if not issued by the court)' },
    { order: 19, stepName: 'Serve opposing party' },
    { order: 20, stepName: 'Pre-trial prep' },
    { order: 21, stepName: 'Trial' },
    { order: 22, stepName: 'Draft submissions', defaultDuration: 14 },
    { order: 23, stepName: 'Further Submissions – if necessary' },
    { order: 24, stepName: 'Attend Court – Judgment & Update client' },
    { order: 25, stepName: 'Pursue decree Nissi' },
    { order: 26, stepName: 'Apply for Decree Absolute' },
    { order: 27, stepName: 'Release documents' },
    { order: 28, stepName: 'Upsell/Downsell other firm services' }
  ],
  'Conveyancing': [ // Mapped from "Real Estate (RE)"
    { order: 1, stepName: 'Take instructions + quote + Call for documents', defaultDuration: 2 },
    { order: 2, stepName: 'Search' },
    { order: 3, stepName: 'Draft/review agreement', defaultDuration: 3 },
    { order: 4, stepName: 'Draft/Review Transfer', defaultDuration: 3 },
    { order: 5, stepName: 'Correspondence', defaultDuration: 3 },
    { order: 6, stepName: 'Valuation after execution of documents', defaultDuration: 3 },
    { order: 7, stepName: 'Stamping' },
    { order: 8, stepName: 'Registration' },
    { order: 9, stepName: 'Release of documents (Upsell other firm services)' }
  ],
  'Succession': [ // Mapped from "Probate & Administration (P & A)"
    { order: 1, stepName: 'Consultation + Quote + Instructions + Request for documents', defaultDuration: 2 },
    { order: 2, stepName: 'Documents received' },
    { order: 3, stepName: 'Drafting after receipt of documents', defaultDuration: 3 },
    { order: 4, stepName: 'Approval and signing' },
    { order: 5, stepName: 'Compiling and filing', defaultDuration: 3 },
    { order: 6, stepName: 'Pay for government printers', defaultDuration: 1 },
    { order: 7, stepName: 'Follow up on gazettement (weekly)' },
    { order: 8, stepName: 'Share gazette notice with client' },
    { order: 9, stepName: 'Follow up on grant' },
    { order: 10, stepName: 'Share grant with client' },
    { order: 11, stepName: 'Give b/u in 5 months' },
    { order: 12, stepName: 'Draft summons for confirmation', defaultDuration: 7 },
    { order: 13, stepName: 'Approval and signing' },
    { order: 14, stepName: 'File summons for confirmation' },
    { order: 15, stepName: 'Inform client of date' },
    { order: 16, stepName: 'Pretrial prep – confirm everything is in place & Mobilize client attendance', defaultDuration: 14 },
    { order: 17, stepName: 'Attend hearing and give court update to client' },
    { order: 18, stepName: 'Extract certificate of confirmation' },
    { order: 19, stepName: 'Extract certified copies of certificate of confirmation' },
    { order: 20, stepName: 'Release documents & UPSELL Transmission' }
  ]
};
